version: "3.8"

services:
  app:
    image: ${IMAGE}
    container_name: bezkoder-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - home/ubuntu/bezkoder-app/bezkoder-app/.env:/home/node/app/.env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
